on:
  push:
    paths:
      - ".github/workflows/ocr.yml"
      - "**.pdf"
jobs:
  ocr:
    name: OCR PDFs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v2
        with:
          enable-cache: true
      - run: rye sync
      - run: python -m paper_collection.ocr_all
      - name: Commit and push changes
        run: |
          git config --local user.name "Steven Hé (Sīchàng)"
          git config --local user.email "sichanghe@users.noreply.github.com"
          git add .
          # Only commit if there are changes
          git diff --exit-code || git commit -m "OCR PDFs of $GITHUB_SHA"
          git pull --rebase
          git push
